version: '3'
services:
  web:
    image: webdevops/php-apache-dev:7.4
    container_name: web_adrian
    restart: "no"
    user: root
    environment:
      - WEB_ALIAS_DOMAIN=127.0.0.1
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=4G
      - PHP_MAX_EXECUTION_TIME=18000
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - COMPOSER_VERSION=2
      - PHP_DEBUGGER=none # comment this parameter to enable xDebug by default
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - XDEBUG_REMOTE_AUTOSTART=1
      # - POSTFIX_RELAYHOST=[mailhog_atlantis]:1025
    volumes:
      - ./:/app:cached
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
      - "32823:22"          
    links:
      - mysql8
      - redis
  mysql8:
    image: mysql:8
    container_name: mysql8_adrian
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=modulosdb
  redis:
    image: redis
    container_name: redis_adrian
    command: --port 6379
    ports:
      - "6379:6379"
    